### ISSUE TITLE
page.ejs中报错body is not defined

### ISSUE THREAD

**Issue by MilkyBoat** [Haojen/hexo-theme-Anisina#106]
使用hexo g命令时，\layout\page.ejs:144行 报error: 
在hexo s后，浏览部分页面也会报同位置error并且无法正常处理请求
```
body is not defined
ReferenceError: D:\Myproject\blog\themes\Anisina\layout\page.ejs:144
    142|     <div class="row">
    143|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">
 >> 144|             <%- body %>
    145|         </div>
    146|         <!-- Sidebar Container -->
    147|         <div class="

body is not defined
    at eval (D:\Myproject\blog\themes\Anisina\layout\page.ejs:29:8)
    at page (D:\Myproject\blog\node_modules\ejs\lib\ejs.js:682:17)
    at viewFn._compiled (D:\Myproject\blog\node_modules\hexo\lib\theme\view.js:136:48)
    at viewFn.View.render (D:\Myproject\blog\node_modules\hexo\lib\theme\view.js:41:15)
    at D:\Myproject\blog\node_modules\hexo\lib\hexo\index.js:61:21
    at tryCatcher (D:\Myproject\blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Myproject\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Myproject\blog\node_modules\hexo\lib\hexo\router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:491:10)
    at resume_ (_stream_readable.js:976:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by yumeko11** [comment]
解决了么

**Comment by Haojen** [comment]
@MilkyBoat @yumeko11 https://github.com/Haojen/hexo-theme-Anisina/issues/37 请两位参考这篇
