### ISSUE TITLE
hexo g报错

### ISSUE THREAD

**Issue by Codingwithme** [Haojen/hexo-theme-Anisina#23]
使用hexo g，报错代码如下，在网上也没有找到解决办法，十分感谢解答。更换其他主题hexo g没有问题

```
$ hexo g
INFO  Start processing
INFO  Files loaded in 371 ms
Unhandled rejection ReferenceError: F:\Hexo\themes\Anisina\layout\page.ejs:127
    125|     <div class="row">
    126|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">
 >> 127|             <%- page.content || body %>
    128|         </div>
    129|     <!-- Sidebar Container -->
    130|             <div class="

body is not defined
    at eval (eval at <anonymous> (F:\Hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:4918)
    at eval (eval at <anonymous> (F:\Hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:12999)
    at F:\Hexo\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (F:\Hexo\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (F:\Hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at F:\Hexo\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (F:\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at F:\Hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\Hexo\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
INFO  Generated: archives/2016/08/index.html
INFO  Generated: archives/index.html
INFO  Generated: 2016/08/30/How-to-use-kindle/index.html
INFO  Generated: 2016/08/31/hexo-install/index.html
INFO  Generated: tags/Kindle/index.html
INFO  Generated: About/index.html
INFO  Generated: tags/Github/index.html
INFO  Generated: tags/Git/index.html
INFO  Generated: tags/Github-Pages/index.html
INFO  Generated: tags/博客/index.html
INFO  Generated: archives/2016/index.html
INFO  Generated: tags/书单/index.html
INFO  Generated: index.html
INFO  Generated: fonts/glyphicons-halflings-regular.woff
INFO  Generated: fonts/glyphicons-halflings-regular.eot
INFO  Generated: fonts/glyphicons-halflings-regular.woff2
INFO  Generated: fonts/glyphicons-halflings-regular.ttf
INFO  Generated: fonts/glyphicons-halflings-regular.svg
INFO  Generated: css/syntax.css
INFO  Generated: css/style.css
INFO  Generated: js/blog.js
INFO  Generated: css/blog-style.css
INFO  Generated: css/bootstrap.min.css
INFO  Generated: js/jquery.tagcloud.js
INFO  Generated: js/totop.js
INFO  Generated: css/bootstrap.css
INFO  Generated: js/jquery.min.js
INFO  Generated: js/bootstrap.min.js
INFO  Generated: js/bootstrap.js
INFO  Generated: js/jquery.js
```

**Comment by perixiaowan** [comment]
page文件有错误

发自 网易邮箱大师
在2016年09月01日 07:59，Codingwithme 写道:

使用hexo g，报错代码如下，在网上也没有找到解决办法，十分感谢解答。更换其他主题hexo g没有问题

$ hexo g
INFO  Start processing
INFO  Files loaded in 371 ms
Unhandled rejection ReferenceError: F:\Hexo\themes\Anisina\layout\page.ejs:127
    125|     <div class="row">
    126|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">

> > 127|             <%- page.content || body %>
> >     128|         </div>
> >     129|     
> >     130|             <div class="

body is not defined
    at eval (eval at <anonymous> (F:\Hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:4918)
    at eval (eval at <anonymous> (F:\Hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:12999)
    at F:\Hexo\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (F:\Hexo\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (F:\Hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at F:\Hexo\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (F:\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at F:\Hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\Hexo\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
INFO  Generated: archives/2016/08/index.html
INFO  Generated: archives/index.html
INFO  Generated: 2016/08/30/How-to-use-kindle/index.html
INFO  Generated: 2016/08/31/hexo-install/index.html
INFO  Generated: tags/Kindle/index.html
INFO  Generated: About/index.html
INFO  Generated: tags/Github/index.html
INFO  Generated: tags/Git/index.html
INFO  Generated: tags/Github-Pages/index.html
INFO  Generated: tags/博客/index.html
INFO  Generated: archives/2016/index.html
INFO  Generated: tags/书单/index.html
INFO  Generated: index.html
INFO  Generated: fonts/glyphicons-halflings-regular.woff
INFO  Generated: fonts/glyphicons-halflings-regular.eot
INFO  Generated: fonts/glyphicons-halflings-regular.woff2
INFO  Generated: fonts/glyphicons-halflings-regular.ttf
INFO  Generated: fonts/glyphicons-halflings-regular.svg
INFO  Generated: css/syntax.css
INFO  Generated: css/style.css
INFO  Generated: js/blog.js
INFO  Generated: css/blog-style.css
INFO  Generated: css/bootstrap.min.css
INFO  Generated: js/jquery.tagcloud.js
INFO  Generated: js/totop.js
INFO  Generated: css/bootstrap.css
INFO  Generated: js/jquery.min.js
INFO  Generated: js/bootstrap.min.js
INFO  Generated: js/bootstrap.js
INFO  Generated: js/jquery.js

**Comment by perixiaowan** [comment]
你把page.ejs文件内容从原项目中重新下一个更新下，试试

发自 网易邮箱大师
在2016年09月01日 07:59，Codingwithme 写道:

使用hexo g，报错代码如下，在网上也没有找到解决办法，十分感谢解答。更换其他主题hexo g没有问题

$ hexo g
INFO  Start processing
INFO  Files loaded in 371 ms
Unhandled rejection ReferenceError: F:\Hexo\themes\Anisina\layout\page.ejs:127
    125|     <div class="row">
    126|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">

> > 127|             <%- page.content || body %>
> >     128|         </div>
> >     129|     
> >     130|             <div class="

body is not defined
    at eval (eval at <anonymous> (F:\Hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:4918)
    at eval (eval at <anonymous> (F:\Hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:12999)
    at F:\Hexo\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (F:\Hexo\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (F:\Hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at F:\Hexo\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (F:\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at F:\Hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\Hexo\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
INFO  Generated: archives/2016/08/index.html
INFO  Generated: archives/index.html
INFO  Generated: 2016/08/30/How-to-use-kindle/index.html
INFO  Generated: 2016/08/31/hexo-install/index.html
INFO  Generated: tags/Kindle/index.html
INFO  Generated: About/index.html
INFO  Generated: tags/Github/index.html
INFO  Generated: tags/Git/index.html
INFO  Generated: tags/Github-Pages/index.html
INFO  Generated: tags/博客/index.html
INFO  Generated: archives/2016/index.html
INFO  Generated: tags/书单/index.html
INFO  Generated: index.html
INFO  Generated: fonts/glyphicons-halflings-regular.woff
INFO  Generated: fonts/glyphicons-halflings-regular.eot
INFO  Generated: fonts/glyphicons-halflings-regular.woff2
INFO  Generated: fonts/glyphicons-halflings-regular.ttf
INFO  Generated: fonts/glyphicons-halflings-regular.svg
INFO  Generated: css/syntax.css
INFO  Generated: css/style.css
INFO  Generated: js/blog.js
INFO  Generated: css/blog-style.css
INFO  Generated: css/bootstrap.min.css
INFO  Generated: js/jquery.tagcloud.js
INFO  Generated: js/totop.js
INFO  Generated: css/bootstrap.css
INFO  Generated: js/jquery.min.js
INFO  Generated: js/bootstrap.min.js
INFO  Generated: js/bootstrap.js
INFO  Generated: js/jquery.js

**Comment by Codingwithme** [comment]
重新下载更新后，还是报这个错误，默认主题可以正常部署

**Comment by Haojen** [comment]
@Codingwithme  因为你的博文内容为空白 : )

**Comment by Codingwithme** [comment]
我重新部署了下，成功了，谢谢解答
