### ISSUE TITLE
hexo g error

### ISSUE THREAD

**Issue by zeyios** [Haojen/hexo-theme-Anisina#3]
I used command "hexo g" and then there was an error:

```
Unhandled rejection ReferenceError: /Users/zeyang/Documents/workspace/bb/themes/Anisina/layout/page.ejs:127
    125|     <div class="row">
    126|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">
 >> 127|             <%- page.content || body %>
    128|         </div>
    129|     <!-- Sidebar Container -->
    130|             <div class="

body is not defined
    at eval (eval at <anonymous> (/Users/zeyang/Documents/workspace/bb/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:5035)
    at eval (eval at <anonymous> (/Users/zeyang/Documents/workspace/bb/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:12609)
    at /Users/zeyang/Documents/workspace/bb/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/Users/zeyang/Documents/workspace/bb/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.<anonymous> (/Users/zeyang/Documents/workspace/bb/node_modules/hexo-renderer-mathjax/index.js:14:24)
    at Hexo.tryCatcher (/Users/zeyang/Documents/workspace/bb/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.ret (eval at <anonymous> (/Users/zeyang/Documents/workspace/bb/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:13:39)
    at /Users/zeyang/Documents/workspace/bb/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/Users/zeyang/Documents/workspace/bb/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/zeyang/Documents/workspace/bb/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/zeyang/Documents/workspace/bb/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/zeyang/Documents/workspace/bb/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/zeyang/Documents/workspace/bb/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/zeyang/Documents/workspace/bb/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/zeyang/Documents/workspace/bb/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by zeyios** [comment]
hexo: 3.1.1
os: Darwin 15.4.0 darwin x64
http_parser: 2.6.2
node: 5.7.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2f

**Comment by Haojen** [comment]
`body is not defined` ,cause in you hexo blogs dirctory , you must be sure you have page files or post files . advice you read hexo Docs [hexo Doc](https://hexo.io/zh-cn/docs/) , and my theme [README](https://github.com/Haojen/hexo-theme-Anisina/blob/master/README.md) .
if this problm still exist , please give you git , i will help you find this proplem ：）

**Comment by zeyios** [comment]
Thank you for response!
I solved this problem by deleting the "tags" and "categories" folders in source.
I don‘t know why.   =。=

**Comment by zeyios** [comment]
Another question.  If I don't use Qiniu images CDN, how can I config my img?

**Comment by Haojen** [comment]
@AsiamCn I known this problem，you don't need delete `tags` and `categories` folder , you just need edit in folders  `index.md` file , in `front matter`add  `layout: tags` , this tags page will be show tags **layout** , in fact , another way  you just edit tags `index.md` write some text just through `hexo g` :),
cause this folder is empty , so hexo g will be show body in not defind..

## about qiniu

you just normal add a images url , like this:

if you images from internet: `http://img3.yxlady.com/xiaomao.jpg`, you just add `header-img: http://img3.yxlady.com/uploads/intro/20120710/1500150.jpg` , etc

or use hexo default img path

`header-img: img/someImages.jpg`

have fun : )

**Comment by zeyios** [comment]
**Thank** you for your help!! I can see my `tags` page now.
But there still some problems.......=。=

When I set `header-img: imgs/post-default.jpg`,it doesn't show a picture.
and I checked the html, it looks like this:

``` html
<style>
    .intro-header{
        background-image:url(
        'imgs/post-default.jpg'
        )
    }
</style>
```

I guess my image path is `http://0.0.0.0:4000/imgs/post-default.jpg` not `http://0.0.0.0:4000/tags/imgs/post-default.jpg`.so It can't get the image.

**Comment by zeyios** [comment]
I solved this problem by setting `header-img: ../imgs/post-default.jpg`and `post-default-img: ../../../../imgs/post-default.jpg`. But it is not so beautiful...

**Comment by zeyios** [comment]
I also don't know why some configs didn't come into effect in `hexoPath/themes/Anisina/_config.yml`, but when I copy them to `hexoPath/_config.yml`, they works.
what's the difference? 
Thank you for your time!

**Comment by Haojen** [comment]
NO **imgs** , is **img/** path.
1. first , git pull my theme new version. today morning update.
2. use **img/someImages.jpg** like this .
3. hexo clean && hexo g && hexo serve , check out : )

if you read my theme `README`, you will know why copy this `_config.yml` in to your blog dircotory by work be fine :)

**Comment by zeyios** [comment]
Oh,**Thank you !!**
