### ISSUE TITLE
去掉body不報錯，首頁不展示文章，打開編譯就會報錯

### ISSUE THREAD

**Issue by seven3s** [Haojen/hexo-theme-Anisina#37]
Unhandled rejection ReferenceError: /Users/liubiao/git/shuangshiji/themes/anisina/layout/page.ejs:145
    143|     <div class="row">
    144|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">

> > 145|             <%- page.content || body%>
> >     146|         </div>
> >     147|         
> >     148|         <div class="

body is not defined
    at eval (eval at <anonymous> (/Users/liubiao/git/shuangshiji/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:4583)
    at eval (eval at <anonymous> (/Users/liubiao/git/shuangshiji/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:12238)
    at /Users/liubiao/git/shuangshiji/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/liubiao/git/shuangshiji/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/liubiao/git/shuangshiji/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/liubiao/git/shuangshiji/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/Users/liubiao/git/shuangshiji/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/liubiao/git/shuangshiji/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/liubiao/git/shuangshiji/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:355:10)
    at resume_ (_stream_readable.js:739:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection ReferenceError: /Users/liubiao/git/shuangshiji/themes/anisina/layout/page.ejs:145
    143|     <div class="row">
    144|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">

> > 145|             <%- page.content || body%>
> >     146|         </div>
> >     147|         
> >     148|         <div class="

body is not defined
    at eval (eval at <anonymous> (/Users/liubiao/git/shuangshiji/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:4583)
    at eval (eval at <anonymous> (/Users/liubiao/git/shuangshiji/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:12238)
    at /Users/liubiao/git/shuangshiji/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/liubiao/git/shuangshiji/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/liubiao/git/shuangshiji/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/liubiao/git/shuangshiji/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/Users/liubiao/git/shuangshiji/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/liubiao/git/shuangshiji/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/liubiao/git/shuangshiji/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:355:10)
    at resume_ (_stream_readable.js:739:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection ReferenceError: /Users/liubiao/git/shuangshiji/themes/anisina/layout/page.ejs:145
    143|     <div class="row">
    144|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">

> > 145|             <%- page.content || body%>
> >     146|         </div>
> >     147|         
> >     148|         <div class="

body is not defined
    at eval (eval at <anonymous> (/Users/liubiao/git/shuangshiji/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:4583)
    at eval (eval at <anonymous> (/Users/liubiao/git/shuangshiji/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:12238)
    at /Users/liubiao/git/shuangshiji/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/liubiao/git/shuangshiji/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/liubiao/git/shuangshiji/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/liubiao/git/shuangshiji/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/Users/liubiao/git/shuangshiji/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/liubiao/git/shuangshiji/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/liubiao/git/shuangshiji/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:355:10)
    at resume_ (_stream_readable.js:739:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Haojen** [comment]
@liubiao0810 这种情况应该是你生成的 md 文件没有写任何内容导致的 :neckbeard:

**Comment by seven3s** [comment]
哦哦，ok。了解

**Comment by zhizionenuo** [comment]
怎么解决的啊，是指我_post里面的文件没有内容吗？我应该都有内容的可为什么我的还是会报错
