### ISSUE TITLE
侧边栏设置后仍不显示

### ISSUE THREAD

**Issue by whyour** [Haojen/hexo-theme-Anisina#48]
侧边栏设置后仍不显示

**Comment by Haojen** [comment]
@w-nba 贴上你设置后的代码， 另外设置后有没有重新部署 hexo deploy -g ?

**Comment by w-nba** [comment]
# SNS settings
# RSS:
weibo_username: haojen
zhihu_username: megahertz
github_username: haojen
twitter_username: ehazon
facebook_username:  
linkedin_username:  

# Build settings
anchorjs: false                        # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings 
disqus_username: 

# Duoshuo settings
duoshuo_username:  w-nba
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id:
# Google Analytics
ga_track_id:             # Format: UA-xxxxxx-xx
ga_domain:

# Sidebar settings
sidebar: true
sidebar-about-description: 石猴博客
sidebar-avatar: /themes/anisina/source/uploads/ggg.png



社交的sns是如何设置的。直接写名字？ @Haojen

**Comment by w-nba** [comment]
![qq 20170311131001](https://cloud.githubusercontent.com/assets/22700758/23820824/132d4200-065c-11e7-9dbc-2114800acf75.png)
@Haojen 
就是这样的显示，本地的。

**Comment by w-nba** [comment]
有什么依赖没装吗。 @Haojen

**Comment by w-nba** [comment]
或者开源下你的例子的配置文件 @Haojen 感觉使用教程略精简。谢谢

**Comment by w-nba** [comment]
配置文件要是站点文件。。
运行hexo g  的时候报错
$ hexo g
INFO  Start processing
INFO  Files loaded in 320 ms
Unhandled rejection ReferenceError: D:\blog\themes\Anisina\layout\page.ejs:145
    143|     <div class="row">
    144|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">
 >> 145|             <%- body %>
    146|         </div>
    147|         
    148|         <div class="

body is not defined
    at eval (eval at <anonymous> (D:\blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:4567)
    at eval (eval at <anonymous> (D:\blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:12220)
    at D:\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (D:\blog\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\blog\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\blog\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
谢谢。

**Comment by w-nba** [comment]
能不能让词是从右往左。谢谢 @Haojen
