### ISSUE TITLE
hexo g报错

### ISSUE THREAD

**Issue by HoeKwan** [Haojen/hexo-theme-Anisina#53]
按默认的config设置，运行hexo g出现很长的报错，没有空的md文件

root@JK-Builder:/opt/hexo# hexo g
INFO  Start processing
INFO  Files loaded in 559 ms
Unhandled rejection ReferenceError: /opt/hexo/themes/Anisina/layout/page.ejs:145
    143|     <div class="row">
    144|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">
 >> 145|             <%- body %>
    146|         </div>
    147|         
    148|         <div class="

body is not defined
    at eval (eval at <anonymous> (/opt/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:4567)
    at eval (eval at <anonymous> (/opt/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:12223)
    at /opt/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/opt/hexo/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/opt/hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at /opt/hexo/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/opt/hexo/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:341:10)
    at RouteStream.Readable.on (_stream_readable.js:720:14)
    at RouteStream.Readable.pipe (_stream_readable.js:575:10)
    at /opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:166:23
    at Promise._execute (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at pipeStream (/opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:161:10)
    at writeFile (/opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:50:12)
    at fs.exists.then.finally.generatingFiles.(anonymous function) (/opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:35:35)
    at tryCatcher (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:458:13)

Unhandled rejection TypeError: /opt/hexo/themes/Anisina/layout/archive.ejs:13
    11|             <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 ">
    12|                 <div class="site-heading text-center">
 >> 13|                     <h1><%= config.archive.title || config.title %></h1>
    14|                     <span class="subheading"><%= config.archive.description || config.subtitle || "" %></span>
    15|                 </div>
    16|             </div>

Cannot read property 'title' of undefined
    at eval (eval at <anonymous> (/opt/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:411)
    at eval (eval at <anonymous> (/opt/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:32:2611)
    at /opt/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/opt/hexo/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/opt/hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at /opt/hexo/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/opt/hexo/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:341:10)
    at RouteStream.Readable.on (_stream_readable.js:720:14)
    at RouteStream.Readable.pipe (_stream_readable.js:575:10)
    at /opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:166:23
    at Promise._execute (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at pipeStream (/opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:161:10)
    at writeFile (/opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:50:12)
    at fs.exists.then.finally.generatingFiles.(anonymous function) (/opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:35:35)
    at tryCatcher (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:458:13)

Unhandled rejection TypeError: /opt/hexo/themes/Anisina/layout/archive.ejs:13
    11|             <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 ">
    12|                 <div class="site-heading text-center">
 >> 13|                     <h1><%= config.archive.title || config.title %></h1>
    14|                     <span class="subheading"><%= config.archive.description || config.subtitle || "" %></span>
    15|                 </div>
    16|             </div>

Cannot read property 'title' of undefined
    at eval (eval at <anonymous> (/opt/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:411)
    at eval (eval at <anonymous> (/opt/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:32:2611)
    at /opt/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/opt/hexo/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/opt/hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at /opt/hexo/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/opt/hexo/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:341:10)
    at RouteStream.Readable.on (_stream_readable.js:720:14)
    at RouteStream.Readable.pipe (_stream_readable.js:575:10)
    at /opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:166:23
    at Promise._execute (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at pipeStream (/opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:161:10)
    at writeFile (/opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:50:12)
    at fs.exists.then.finally.generatingFiles.(anonymous function) (/opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:35:35)
    at tryCatcher (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:458:13)

Unhandled rejection TypeError: /opt/hexo/themes/Anisina/layout/archive.ejs:13
    11|             <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 ">
    12|                 <div class="site-heading text-center">
 >> 13|                     <h1><%= config.archive.title || config.title %></h1>
    14|                     <span class="subheading"><%= config.archive.description || config.subtitle || "" %></span>
    15|                 </div>
    16|             </div>

Cannot read property 'title' of undefined
    at eval (eval at <anonymous> (/opt/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:411)
    at eval (eval at <anonymous> (/opt/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:32:2611)
    at /opt/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/opt/hexo/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/opt/hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at /opt/hexo/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/opt/hexo/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:341:10)
    at RouteStream.Readable.on (_stream_readable.js:720:14)
    at RouteStream.Readable.pipe (_stream_readable.js:575:10)
    at /opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:166:23
    at Promise._execute (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at pipeStream (/opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:161:10)
    at writeFile (/opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:50:12)
    at fs.exists.then.finally.generatingFiles.(anonymous function) (/opt/hexo/node_modules/hexo/lib/plugins/console/generate.js:35:35)
    at tryCatcher (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/opt/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:458:13)

INFO  Generated: 2017/04/09/hello-world/index.html
INFO  Generated: index.html
INFO  Generated: fonts/glyphicons-halflings-regular.ttf
INFO  Generated: fonts/glyphicons-halflings-regular.eot
INFO  Generated: css/blog-style.css
INFO  Generated: css/syntax.css
INFO  Generated: res/avatar.jpg
INFO  Generated: fonts/glyphicons-halflings-regular.woff
INFO  Generated: fonts/glyphicons-halflings-regular.woff2
INFO  Generated: js/blog.js
INFO  Generated: js/bootstrap.min.js
INFO  Generated: js/jquery.tagcloud.js
INFO  Generated: js/totop.js
INFO  Generated: css/bootstrap.min.css
INFO  Generated: fonts/glyphicons-halflings-regular.svg
INFO  Generated: js/jquery.min.js
INFO  Generated: js/jquery.js

**Comment by eliiik** [comment]
同样报错，md文件内有内容

**Comment by emma-sjwang** [comment]
我也是，求解决方案

**Comment by Haojen** [comment]
这个问题目前我还没有复现出来, 但会尽快解决. 多谢你的反馈,找到问题的解决方法后会及时在此告知大家, 谢谢诸位的支持

**Comment by BiYuqi** [comment]
@Haojen  我的也遇到类似 body is not undefined 的报错提示，不过能正常部署，目前最大的问题是移动端直接下半部分不显示

**Comment by BiYuqi** [comment]
##### 我提供下上面的报错信息
![](http://oiukswkar.bkt.clouddn.com/blog-theme-bug2.png)

**Comment by marszoolong** [comment]
我的问题是这样：hexo new page "tags", 默认生成的 source/tags/index.md 如下：
---
**title: tags**
....
---
**不是官网上说的 layout : tags**
改正之后不会再报此错误，但是菜单不会显示tags，但点击每篇文章的tags，又能进入 tags 页面

over！

**Comment by WeihuaGu** [comment]
更换其它主题，一样报错，然后发现主题没有换过来
觉得关键在下面这个，不懂。网上有人说layout 里用locals.title什么的不懂。
```
at eval (eval at <anonymous> (/home/better/project/bookfindhexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:49)
```
我的hexo版本为：
```
hexo: 3.3.7
hexo-cli: 1.0.2
os: Linux 4.4.0-79-generic linux ia32
http_parser: 2.5.0
node: 4.2.6
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 55.1
modules: 46
openssl: 1.0.2g-fips
```

**Comment by handsameliu** [comment]
同样出现相同问题，可以启动但只有主页和文章页可以正常查看。标签及标签页，友情链接均无法显示。
因为我一开始使用的是yilia和next这两个主题，这俩可以正常运行。@marszoolong 所说的方法也试过了也不好使。以下是配置。
```
hexo: 3.3.7
hexo-cli: 1.0.3
os: Windows_NT 10.0.15063 win32 x64
http_parser: 2.7.0
node: 6.11.0
v8: 5.1.281.102
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
```

**Comment by fingthinking** [comment]
我也是出现同样类似的错误，使用`hexo new page test`出现的错误，请作者查看
```JavaScript
Unhandled rejection ReferenceError: /Users/liuruteng/blog/fingthinking/themes/Anisina/layout/page.ejs:145
    143|     <div class="row">
    144|         <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-sm-12 col-xs-12 post-container">
 >> 145|             <%- body %>
    146|         </div>
    147|         <!-- Sidebar Container -->
    148|         <div class="

body is not defined
    at eval (eval at exports.compile (/Users/liuruteng/blog/fingthinking/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:4567)
    at eval (eval at exports.compile (/Users/liuruteng/blog/fingthinking/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:12223)
    at /Users/liuruteng/blog/fingthinking/node_modules/ejs/lib/ejs.js:255:15
    at Theme._View.View._compiled (/Users/liuruteng/blog/fingthinking/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/Users/liuruteng/blog/fingthinking/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/liuruteng/blog/fingthinking/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/Users/liuruteng/blog/fingthinking/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/liuruteng/blog/fingthinking/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/liuruteng/blog/fingthinking/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:431:10)
    at resume_ (_stream_readable.js:811:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by hx1997** [comment]
不太清楚 body is not defined 的问题，不过 Cannot read property 'title' of undefined 的问题我解决了，在 _config.yml 加上这一段就行了：

```
# archive page title 
archive:
    title: archives
```

看来最好还是把作者给的 _config.yml 复制过来改，不要用以前主题的配置。。。
还有在 Windows 下最好把主题根目录和 /layout 目录下的 .DS_Store 删掉。

**Comment by fingthinking** [comment]
@handsameliu @GaHoKwan @dogabner @EmmaW8 @Haojen @BiYuqi @hx1997 @WeihuaGu @YYGCui @HipHopCoderS 应该都@全了吧，我也是遇到了对应的问题，经过几天摸索，成功解决，给出解决方案  
[Hexo及Anisina使用心得](https://fingthinking.github.io/2017/08/05/Hexo%E5%8F%8AAnisina%E4%BD%BF%E7%94%A8%E5%BF%83%E5%BE%97/#问题2-使用Anisina主题，hexo-new-page-xxx之后，hexo-g报错？)

**Comment by Hstb1230** [comment]
上个版本未出现这样问题，后来我仔细去对比代码，发现148行的`<%- page.content || body %>`被改成`<%- body %>`

**Comment by ChadDongDongChen** [comment]
同上，我hexo g也遇到同样的问题。
![image](https://user-images.githubusercontent.com/20555258/41635841-8dea449e-747d-11e8-8740-77295b9ad0b9.png)

**Comment by YUTING0907** [comment]
> 上个版本未出现这样问题，后来我仔细去对比代码，发现148行的`<%- page.content || body %>`被改成`<%- body %>`

我把<%- body %>改成<%- page.content || body %>，没有报错了，但是好像文章的排版会很奇怪，不知道是什么问题

**Comment by t34shen** [comment]
同样遇到body undefined的问题无法generate，请问有什么解决办法吗

**Comment by erenlu** [comment]
> 不太清楚 body is not defined 的问题，不过 Cannot read property 'title' of undefined 的问题我解决了，在 _config.yml 加上这一段就行了：
> 
> ```
> # archive page title 
> archive:
>     title: archives
> ```
> 
> 看来最好还是把作者给的 _config.yml 复制过来改，不要用以前主题的配置。。。
> 还有在 Windows 下最好把主题根目录和 /layout 目录下的 .DS_Store 删掉。

感谢你曾经的回答，今天拍了大半个下午也没找到。 最后加上
> # archive page title 
> archive:
>     title: archives
就解决了
